a = input("Enter the first number:" )
b = input ("Enter the second number:" )
c = int(a) + int(b)
print("The addition of your two numbers is:", c)
c = int(a) - int(b)
print("The subtraction of your two numbers is:", c)
c = int(a) * int(b)
print("The multiplication of your two numbers is:", c)
c = int(a) / int(b)
print("The divition of your two numbers is:", c)
c = int(a) % int(b)
print("The exponential of your two numbers is:", c)
c = int(a) // int(b)
print("The floor division of your two numbers is:", c)

